// for my adjustments to the code generator, I made it college/UMW themed!

let poem = '';

let grammar = tracery.createGrammar({
  "origin": ["A HOUSE OF #material# #place# #lightSource# #inhabitants#."],
  "material": [
    "PIZZA BOXES", "COFFEE CUPS", "TEXTBOOKS", "NOTEBOOKS", "PLASTIC BOTTLES", 
    "POSTERS", "BEANBAGS", "LANYARDS", "STICKERS", "DORM FURNITURE", 
    "DRY ERASE MARKERS", "BACKPACKS", "SNEAKERS", "HOODIES"
  ],
  "place": [
    "IN A DORM ROOM", "IN A STUDY LOUNGE", "IN A LECTURE HALL", 
    "IN THE LIBRARY", "IN A BOOTH AT PANERA", "IN THE MUSIC HALL", "IN THE REC CENTER", 
    "IN A LABORATORY", "IN THE DINING HALL", "IN A FRAT HOUSE", 
    "IN THE UNIVERSITY CENTER", "IN THE HCC", 
    "IN A PROFESSOR'S OFFICE", "IN THE PARKING LOT"
  ],
  "lightSource": [
    "USING STRING LIGHTS", "USING A DESK LAMP", "USING A LAPTOP SCREEN", 
    "USING PHONE FLASHLIGHTS", "USING FAIRY LIGHTS", "USING A PROJECTOR", 
    "USING THE GLOW OF A VENDING MACHINE", "USING A STREETLIGHT OUTSIDE", 
    "USING A TV SCREEN", "USING A BONFIRE", "USING STUDY LAMPS", 
    "USING A TORCH FROM A THEATER PRODUCTION", "USING FLUORESCENT LIGHTS", 
    "USING THE MOON", "USING A LATE-NIGHT CAMPUS AMBIENCE"
  ],
  "inhabitants": [
    "INHABITED BY STUDY GROUPS", "INHABITED BY PROCRASTINATORS", 
    "INHABITED BY ROOMMATES WHO NEVER CLEAN", "INHABITED BY GAMERS", 
    "INHABITED BY STRESSED-OUT STUDENTS", "INHABITED BY PARTYGOERS", 
    "INHABITED BY THEATER KIDS", "INHABITED BY CLUB MEETING MEMBERS", 
    "INHABITED BY LATE-NIGHT SNACKERS", "INHABITED BY FRIENDS WORKING ON A GROUP PROJECT", 
    "INHABITED BY SLEEP-DEPRIVED STUDENTS", "INHABITED BY DEBATE TEAM MEMBERS", 
    "INHABITED BY CAMPUS TOUR GUIDES", "INHABITED BY RESIDENT ADVISORS", 
    "INHABITED BY ALUMNI REMINISCING"
  ]
});

function setup() {
  createCanvas(800, 800);
  frameRate(0.25);
}

function draw() {
  background(220);
  poem = grammar.flatten("#origin#");
  textFont("monospace");
  textSize(24);
  fill(0);
  text(poem, 50, 200, 700, 400);
}